### ISSUE TITLE
Remove the clientId and client secret from Node.js/config/passport-setup.js and put it in an ENV file

### ISSUE THREAD

**Issue by jugaldb** [CodeChefVIT/OAuth-Pro#16]
Currently the Google Client ID and Client Secret are in the code itself and that is not a good practice, remove them and put it in an .env file

**Comment by SEdilson** [comment]
@jugaldb could I work on this one?

**Comment by jugaldb** [comment]
@SEdilson This is currently a work in progress https://github.com/CodeChefVIT/OAuth-Pro/pull/19

If it has no updates by the end of today we will assign it to you.

**Comment by DiptoChakrabarty** [comment]
@rvjain0510  are you going to continue on this or else @SEdilson  can pick it up from here

**Comment by akshatvg** [comment]
Due to no follow back for a while by the original developer, I’ll assign you @SEdilson ✌🏻

**Comment by SEdilson** [comment]
Hey @akshatvg, as requested here's the PR #23 to solve this issue. Thanks for letting me contribute.

**Comment by jugaldb** [comment]
PR merged, closing the issue thanks @SEdilson
