### ISSUE TITLE
OAuth for GoLang

### ISSUE THREAD

**Issue by DiptoChakrabarty** [CodeChefVIT/OAuth-Pro#6]
Add the OAuth GoLang codes in a separate GoLang directory for the following:
 - Github
- Google
- Linkedln
- Twitter
- FaceBook
- Spotify

Each assignee will be allotted one of the following from above mentioned ones at a time. To include any other application feel free to mention them.

Make sure to read the contribution guidelines and follow the flow given in the README.md file.

**Comment by prithvijit-dasgupta** [comment]
Hey I am learning GoLang. Would like to attempt this.  Is anyone else working on this?

**Comment by DiptoChakrabarty** [comment]
Sure @prithvijit-dasgupta  go ahead , oauth for google has been completed and the rest are remaining just so you know

**Comment by prithvijit-dasgupta** [comment]
@DiptoChakrabarty the expection is to return the auth token to the API invoker, am I correct?

**Comment by N0v0cain3** [comment]
6a9082c822a6d59d9892989dfaf717514275b6ca
